name: Post checkout

description: Post checkout instructions.

runs:
  using: "composite"
  steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - uses: gradle/actions/setup-gradle@v3
